
\set ON_ERROR_STOP on

CREATE TABLE app.machinegroup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    orgnr INTEGER NOT NULL,
    code VARCHAR(100) NOT NULL,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    FOREIGN KEY (orgnr) REFERENCES base.org(nr)
);

CREATE TABLE app.machine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    orgnr INTEGER NOT NULL,
    classification INTEGER,
    machinegroupid BIGINT,
    stationpairs INTEGER NOT NULL,
    code VARCHAR(100) NOT NULL,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    FOREIGN KEY (orgnr) REFERENCES base.org(nr),
    FOREIGN KEY (machinegroupid) REFERENCES app.machinegroup(id)
);



/*
create table country
(
	id bigserial primary key,
	image varchar
) INHERITS (app.baseref);
alter table country OWNER to postgres;
alter sequence country_id_seq restart with 10000;

create table currency
(
	id bigserial primary key	
) INHERITS (app.baseref);
alter table currency OWNER to postgres;
alter sequence currency_id_seq restart with 10000;
*/